### ISSUE TITLE
High level project architecture diagram

### ISSUE THREAD

**Issue by charithsoori** [99xt/aws-userpool-boilerplate#4]

**Comment by chamathpali** [comment]
@AshanFernando  @charithsoori  attached the high level diagram. these will be the basic functions provided by the boilerplate.

![aws user pool boiler architecture](https://cloud.githubusercontent.com/assets/5123109/18832830/2a5bcea2-840b-11e6-83a3-2a1c97db4283.png)

**Comment by chamathpali** [comment]
Added.
